name: cancure
description: UI for Cancure

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable:
  provider:
  cupertino_icons: ^1.0.0
  animated_text_kit: ^3.1.0
  firebase_core:
  firebase_auth: ^0.20.0+1
  cloud_firestore:
  intl: ^0.16.0
  modal_progress_hud: ^0.1.3
  curved_navigation_bar: ^0.3.7
  percent_indicator: "^2.1.7+2"
  image_picker: ^0.6.7+21
  http: ^0.12.2
  dio: ^3.0.10
  progress_dialog: ^1.2.4
  grouped_buttons: ^1.0.4
  group_button:
  search_page: ^1.3.0
  cached_network_image: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#42a5f5"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/CardImages/

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
